### ISSUE TITLE
Pub version is bugged

### ISSUE THREAD

**Issue by Kleak** [google/charted#119]
The pub version is not working the following error is throw : 
Exception: Uncaught Error: Invalid argument (value): Not a valid class token: "bar-rdr-bar "﻿

The version on github work great !
Please update the version on pub :)
Thanks

**Comment by psunkari** [comment]
Hi Kleak, thanks for the report.
We will be pushing a new version later today.

**Comment by psunkari** [comment]
Pushed 0.2.4
