### ISSUE TITLE
I can't show more than 6 lines in one chart

### ISSUE THREAD

**Issue by kelegorm** [google/charted#131]
I want to show in one chart more than 6 lines. How I can to do it? I have tried this: 

    var measures = [];
    for (int i = 1; i < data.columns.length && i < 7; i++) {
      measures.add(i);
    }

    var series = new ChartSeries("one", measures, new LineChartRenderer()),

then config, area, draw...

As you can see I have destriction to 6 measure numbers in `measures` list. But when I try to add one more I get some error:

    Exception: Uncaught Error: RangeError: index (7) must be in the range [0..7)
    Stack Trace: 
    #0      List.[] (dart:core-patch/growable_array.dart:136)
    #1      List.elementAt (dart:core-patch/growable_array.dart:308)
    #2      CartesianRendererBase.extent (package:charted/charts/cartesian_renderers/cartesian_base_renderer.dart:91:25)
    #3      _CartesianArea._initAxes.<anonymous closure>.<anonymous closure> (package:charted/charts/src/cartesian_area_impl.dart:385:63)
    #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
    #5      ListIterable.toList (dart:_internal/iterable.dart:219)
    #6      _CartesianArea._initAxes.<anonymous closure> (package:charted/charts/src/cartesian_area_impl.dart:385:71)

I have tried to create 7 different Line Chart Renderers but it cause same error. I have delving in sourses but can't find restrictions for line count.

Is it possible to show more than 6 lines and how to get it? Thanks.

**Comment by psunkari** [comment]
Hi Dmitriy,
Thanks for the report.  I will take a look at it.

**Comment by kelegorm** [comment]
Sorry, it was my bug, another issue. Wrong data in input.

So, problem was I have rows with different length. In this case count of columns was as shortest row length and charts can't display other lines.
