### ISSUE TITLE
Hovercard has wrong label with pie chart

### ISSUE THREAD

**Issue by johnmccutchan** [google/charted#140]
Hovercard has wrong label with pie chart

Pie slice: Dart - 43.53%
Hovercard shows: Idle 0.0

Pie slice: GCNewSpace 38.57%
Hovercard shows: LoadWait 7.88%

Both Idle and LoadWait are part of the pie chart but the hovercard mouse over seems confused.

**Comment by johnmccutchan** [comment]
I have tried explicitly requesting mouse tracking and that does not resolve the issue.

**Comment by johnmccutchan** [comment]
This may have something to do with #144 (the pie chart rows are being sorted)...

**Comment by psunkari** [comment]
Thanks for reporting the issue.  Fixed in https://github.com/google/charted/pull/148
