### ISSUE TITLE
Pie chart colors are unstable

### ISSUE THREAD

**Issue by johnmccutchan** [google/charted#144]
The pie chart colors change based on which column has the highest value. This makes the pie chart unstable and unreadable when the values are changing.

**Comment by johnmccutchan** [comment]
Initially used is 95.54% and is assigned the blue color:

<img width="655" alt="used_blue" src="https://cloud.githubusercontent.com/assets/224266/9430445/fa3e5852-49aa-11e5-9522-0bdd0d10f0ae.png">

After a GC free is now 86.33% and is assigned the blue color:

<img width="653" alt="free_blue" src="https://cloud.githubusercontent.com/assets/224266/9430446/faa69282-49aa-11e5-8c45-d1e1cc7e8e84.png">

**Comment by psunkari** [comment]
We could make sorting of pies by value optional.  By making that optional, the palette and the order of pies (including legend) will be much more stable (and directly based on the input data)

Does that sound good?
