### ISSUE TITLE
hashCode needs to be implemented for Rect and AbsoluteRect

### ISSUE THREAD

**Issue by johnmccutchan** [google/charted#158]
dart2js highlighting issues:

[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/charted/core/utils/rect.dart:22:16:
The class 'Rect' overrides 'operator==', but not 'get hashCode'.
  bool operator==(other) =>
               ^^
[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/charted/core/utils/rect.dart:58:16:
The class 'AbsoluteRect' overrides 'operator==', but not 'get hashCode'.
  bool operator==(other) =>
               ^^

**Comment by hterkelsen** [comment]
Please fix this, it's an eyesore on every single dart SDK build

**Comment by psunkari** [comment]
Fixed in 0.3
