### ISSUE TITLE
Warnings present in every build of Observatory against charted 0.3.0

### ISSUE THREAD

**Issue by johnmccutchan** [google/charted#167]
[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/charted/selection/src/transition_impl.dart:145:32:
The element type 'Map' of 'List<Map>' is not assignable to 'Interpolator'.
    for (Interpolator tween in _attrMap[activeNode]) {
                                             ^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
packages/charted/core/utils/color.dart:279:26:
No member named 'iterator' in class 'String'.
      for (final char in hex) {
                               ^^^

**Comment by johnmccutchan** [comment]
Would be great if these could be fixed and a new release uploaded to pub soon.

**Comment by johnmccutchan** [comment]
*ping*

**Comment by kaendfinger** [comment]
See #170 for a fix :)

**Comment by johnmccutchan** [comment]
@psunkari ping

**Comment by psunkari** [comment]
We will push a new version in a couple of days.

**Comment by johnmccutchan** [comment]
@psunkari Will this release will be free of dart2js compilation warnings?

**Comment by B3rn475** [comment]
Observatory moved to version 0.4.8 I think we can close this issue.

Related https://github.com/dart-lang/sdk/commit/a67d798841ec6379c39c6cd20e9b867689df0e64
